/**********************
****[100% REVISADO]****
***********************/
#define TXT_DebugInfo "Carregamento do server..."
#define TXT_HousesFixed "Casas criadas: %i"
#define TXT_LastVehicleID "Carros carregados: %i"
#define TXT_LastObjectID "Objetos carregados: %i"
#define TXT_TotalHouses "Casas carregadas: %i"
#define TXT_TotalBusiness "Empresas carregadas: %i"
#define TXT_TotalSpeedCameras "Radares carregados: %i"
                                                                                //OK
#define TXT_PlayerJoinedServer "{808080}O jogador {FFFF00}%s{808080} (id: {FFFF00}%i{808080}) {00FF00}entrou{808080} no server."
#define TXT_PlayerLeftServer "{808080}O jogador {FFFF00}%s{808080} (id: {FFFF00}%i{808080}) {FF0000}saiu{808080} do server."
                                                                                //OK
#define TXT_StillBanned "{FF0000}Você ainda está banido."
#define TXT_BannedDuration "{FF0000}Faltam %i dias %i horas %i minutos e %i segundos." 
#define TXT_KickSpeedHack "{FF0000}Você foi kicado por usar speed-hack e/ou air-brake."
#define TXT_KickJetPackHack "{FF0000}Você foi kickado por usar jetpack-hack."
#define TXT_KickHealthHack "{FF0000}Você foi kicado por usar health-hack."
                                                                                //OK
#define TXT_DialogButtonCancel "Cancelar"
#define TXT_DialogButtonBuy "Comprar"
#define TXT_DialogButtonSpawn "Spawn"
#define TXT_DialogButtonSelect "Selecionar"
#define TXT_DialogButtonYes "Sim"
#define TXT_DialogButtonNo "Não"
                                                                                //OK
#define TXT_DialogEntryNext "Proximo"
                                                                                //OK
#define TXT_DialogRegisterTitle "Bem Vindo"
#define TXT_DialogRegisterMsg "Por Favor registre com sua senha de entrada:"
#define TXT_DialogRegisterButton1 "Registrar"
#define TXT_AccountRegistered "{00FF00}Conta registrada com sucesso!"
#define TXT_RegisterEnterValidPassword "Insira uma senha válida para registrar:"
#define TXT_PlayerMustRegister "{FF0000}Você precisa se registrar-se para poder jogar, porisso foi kickado!"
                                                                                //OK
#define TXT_DialogLoginTitle "Brasil Mega Trucker"
#define TXT_DialogLoginMsg "Insira sua senha para logar:"
#define TXT_DialogLoginButton1 "Logar"
#define TXT_LoggedIn "{00FF00}...:::Bem Vindo novamente ao Brasil Mega Trucker::..."
#define TXT_WrongPassword "{FF0000}Você inseriu a senha errada e por motivos de segurança foi kickado."
#define TXT_LoginEnterValidPassword "Insira a senha correta para logar:"
#define TXT_PlayerMustLogin "{FF0000}Você precisa logar-se para jogar, porisso foi kickado."
#define TXT_FailedLoginProperly "{FF0000}Você não conseguiu logar corretamente, porisso foi kickado."
                                                                                //OK
#define TXT_DialogLicenseTitle "Selecionar licença:"
#define TXT_DialogLicenseList "Caminhão (R$50.000 + 100 scores)\r\nÔnibus (R$25.000 + 50 scores)\r\nPorte de Armas (R$100.000 + 200 scores)"
                                                                                //OK
#define TXT_PickupText "Licenciamentos"
                                                                                //OK
//Caminhão
#define TXT_TruckerLicenseBought "{00FF00}Você adquiriu a licença de caminhoneiro!"
#define TXT_TruckerLicenseNotEnoughMoney "{FF0000}Você precisa de R$50.000 e 100 scores para comprar a licença de caminhoneiro!"
#define TXT_TruckerLicenseOwned "{FF0000}Você já possui essa licença!"
#define TXT_TruckerLicenseWrongClass "{FF0000}Você precisa ser caminhoneiro para comprar essa licença."
                                                                                //OK
//Onibus
#define TXT_BusLicenseBought "{00FF00}Você adquiriu a licenca de ônibus!"
#define TXT_BusLicenseNotEnoughMoney "{FF0000}Você precisa de R$25.000 e 50 scores para comprar a licença de ônibus."
#define TXT_BusLicenseOwned "{FF0000}Você já possui essa licença!"
#define TXT_BusLicenseWrongClass "{FF0000}Você precisa ser motorista de ônibus para comprar essa licença."
                                                                                //OK
//Armas
#define TXT_WeaponLicenseBought "{00FF00}Você adquiriu o porte de armas!"
#define TXT_WeaponLicenseNotEnoughMoney "{FF0000}Você precisa de R$100.000 e 200 scores para comprar o porte de armas."
#define TXT_WeaponLicenseOwned "{FF0000}Você já possui o porte de armas!"
                                                                                //OK
#define TXT_DialogCarTitle "Escolha o carro (pag %i):"
#define TXT_DialogPlaneTitle "Escolha o aviao (pag %i):"
#define TXT_DialogTrailerTitle "Escolha o trailer (pag %i):"
#define TXT_PlayerSpawnedVehicle "{00FF00}%s criou o veiculo %i [%i].     (X:%4.2f | Y=%4.2f | Z=%4.2f)"
#define TXT_ChangedWeather "{00FF00}Você alterou o clima!")
#define TXT_DialogCommandTitle "Lista de comandos (pag %i):"
                                                                                //OK
// Trucker related
#define TXT_PlayerCompletedTruckJob "{FF8000}[ANTT] {FFFFFF}%s {FF8000}transportou {FFFFFF}%s{FF8000}."   
#define TXT_PlayerLocationTruckJob "{FF8000}De: {FFFFFF}%s {FF8000}Para: {FFFFFF}%s{FF8000}." 
#define TXT_TruckerBonusOverloaded "{00FF00}Você ganhou um bônus por estar sobrecarregado: R$%i."
#define TXT_TruckerBonusMafiaLoad "{00FF00}Você ganhou um bônus por carregar uma carga de interesse da máfia: R$%i."
#define TXT_TruckerBonusOwnVehicle "{00FF00}Você ganhou um bônus por fretar com seu caminhão: R$%i."
#define TXT_TruckerMustEnterVehicle "{FF0000}Entre de volta no seu veiculo ou re-atrele o trailer!"
#define TXT_TruckerOverloaded "{FF0000}Você está sobrecarregado! Evite a polícia."
#define TXT_TruckerMafiaInterested "~r~A Mafia esta interessada em sua carga~w~"
#define TXT_TruckerDialogSelectLoad "Selecione a carga:"
#define TXT_TruckerDialogSelectStartLoc "Selecione o ponto de carga:"
#define TXT_TruckerDialogSelectEndLoc "Selecione o ponto de descarga:"
#define TXT_NeedVehicleToProceed "{FF0000}Você precisa estar no seu veiculo para prosseguir!"
#define TXT_NeedTrailerToProceed "{FF0000}Você precisa estar com o seu trailer atrelado para proseguir!"
#define TXT_NeedOnFootToProceed "{FF0000}Você precisa estar a pé para proseguir!"
                                                                                //OK
// Busdriver related
#define TXT_PlayerCompletedBusLine "{00FFFF}[ANTT] {FFFFFF}%s {00FFFF}completou a rota {FFFFFF}%i {00FFFF}com sucesso!"
#define TXT_BusDriverMissionPassed "Missao terminada" 
#define TXT_BusDriverJobInfo "~w~Linha ~y~%i~w~ (~g~%s~w~): ~b~%i~w~ no onibus"
#define TXT_BusDriverBusStopInfo "~w~Linha ~y~%i~w~ (~g~%s~w~): ~b~%i~w~ no onibus, ~b~%i~w~ no ponto"
#define TXT_BusDriverReward "~b~Voce ganhou ~g~R$%i~w~"
#define TXT_BusDriverMustEnterBus "{FF0000}Voce precisa entrar em um onibus"
#define TXT_SelectBusRoute "Selecione a rota:"
#define TXT_BusdriverAlreadyDoingJob "{FF0000}Voce ja esta trabalhando."
                                                                                //OK
// Mafia related                                                          
#define TXT_PlayerCompletedMafiaJob "{8000FF}O Mafioso {FFFFFF}%s {8000FF}transportou {FFFFFF}%s{8000FF}."
#define TXT_PlayerLocationMafiaJob "{8000FF}De: {FFFFFF}%s {8000FF}Para: {FFFFFF}%s {8000FF}."
#define TXT_MafiaMustEnterVehicle "{FF0000}Voce precisa estar no seu veiculo"
#define TXT_MafiaDeliverStolenLoad "~w~Leve ~b~a carga roubada~w~ para o ~r~esconderijo~w~"
#define TXT_MafiaDeliveredStolenLoad "{00FF00}Voce entregou a carga roubada, voce ganhou R$5000"
                                                                                //OK
// Police related
#define TXT_PoliceWarnPlayer "~r~Policia! ~n~~w~por favor ~n~ encoste o veiculo!~n~~r~--~w~-~b~--~w~"
#define TXT_PoliceFinedPlayerReward "{00FF00}Você mutou %s e ganhou R$%i."
#define TXT_PlayerGotFinedByPolice "{FF0000}Você foi multado por %s, e pagou uma multa no valor de R$%i."
#define TXT_PoliceFinedPlayer "{0000FF}[Departamento de Polícia] O Oficial {FFFFFF}%s {0000FF}multou {FFFFFF}%s{0000FF}."
#define TXT_PoliceJailedPlayerReward "{00FF00}Você prendeu %s e ganhou R$%i."
#define TXT_PlayerGotJailedByPolice "{FF0000}Voce foi preso por %s durante %i minutos."
#define TXT_PoliceJailedPlayer "{0000FF}[Departamento de Polícia] O Oficial {FFFFFF}%s {0000FF}prendeu {FFFFFF}%s {0000FF}por {FFFFFF}%i {0000FF}minutos."
                                                                                //OK
// Pilot related
#define TXT_PlayerCompletedPilotJob "{008080}O Piloto {FFFFFF}%s {008080}transportou {FFFFFF}%s{008080}."
#define TXT_PlayerLocationPilotJob "{008080}De: {FFFFFF}%s {008080}Para: {FFFFFF}%s{008080}."
                                                                                //OK
// Courier related
#define TXT_CourierMustEnterVehicle "{FF0000}Entregue o pacote e volte para o carro!"    
#define TXT_PlayerCompletedCourierJob "{FF00FF}[SEDEX] O Agente dos correios {FFFFFF}%s {FF00FF}entregou {FFFFFF}%i {FF00FF}pacotes com sucesso!"
#define TXT_PackageDeliveredGameText "Pacote entregue!"
#define TXT_PackageDeliveredMessage "{00FF00}Pacote entregue!"
                                                                                //OK
// Roadworker related
#define TXT_RepairSpeedcamera "~w~Repare o ~r~radar~w~ indicado"
#define TXT_TowBrokenVehicle "~w~guinche o ~r~veiculo quebrado~w~ de ~b~%s~w~ para o triturador"
#define TXT_DeliverBrokenVehicle "~w~guinche o veiculo quebrado de ~b~%s~w~ para o ~r~triturador~w~"
#define TXT_RoadworkerMustEnterVehicle "{FF0000}Voce precisa voltar para o veiculo ou re-atrelar o trailer."
#define TXT_RoadworkerMissionPassed "Missao finalizada"
                                                                                //OK
// Job related, for all classes
#define TXT_RewardJob "{00FF00}Voce finalizou a entrega e ganhou R$%i."         
#define TXT_FailedMission "~w~Voce ~r~falhou~w~ na missao. e perdeu ~y~R$1000~w~ para cobrir as despesas." 
                                                                                //OK
// Class related
#define TXT_ClassTrucker "~r~Caminhoneiro" // Define the game-text that shows when the player is choosing classes (this one = trucker)
#define TXT_ClassBusDriver "~b~Motorista de Onibus" // Define the game-text that shows when the player is choosing classes (this one = bus-driver)
#define TXT_ClassPilot "~w~Piloto de Aviao" // Define the game-text that shows when the player is choosing classes (this one = pilot)
#define TXT_ClassPolice "~b~Policia" // Define the game-text that shows when the player is choosing classes (this one = police)
#define TXT_ClassMafia "~r~Mafia" // Define the game-text that shows when the player is choosing classes (this one = mafia)
#define TXT_ClassCourier "~p~Correios" // Define the game-text that shows when the player is choosing classes (this one = courier)
#define TXT_ClassAssistance "~g~Mecanico" // Define the game-text that shows when the player is choosing classes (this one = assistance)
#define TXT_ClassRoadWorker "~y~operario~n~DNIT" // Define the game-text that shows when the player is choosing classes (this one = roadworker)
                                                                                //OK
// No-job texts for all classes
#define Trucker_NoJobText "Nenhum trabalho no momento. Use \"~y~/trabalhar~w~\" para comecar a trabalhar"
#define BusDriver_NoJobText "Nenhum trabalho no momento. Use \"~y~/trabalhar~w~\" para comecar a trabalhar"
#define Pilot_NoJobText "Nenhum trabalho no momento. Use \"~y~/trabalhar~w~\" para comecar a trabalhar"
#define Police_NoJobText "~r~'RMB'~w~ para multar (a pe), ~r~'LCTRL'~w~ para avisar um jogador (no carro)"
#define Mafia_NoJobText "Aguarde um ~r~veiculo~w~ para roubar ou use \"~y~/trabalhar~w~\" para transportar"
#define Courier_NoJobText "Nenhum trabalho no momento. Use \"~y~/trabalhar~w~\" para comecar a trabalhar"
#define Assistance_NoJobText "~r~'RMB'~w~ reparar/abastecer um carro (a pe), ~r~'LCTRL'~w~ repara seu veiculo"
#define RoadWorker_NoJobText "Nenhum trabalho no momento. Use \"~y~/trabalhar~w~\" para iniciar um trabalho"
                                                                                //OK
// Command related
#define TXT_PlayerRescued "{FF0000}Você foi resgatado! Isso lhe custou: {00FF00}R${FFFFFF}200{FF0000}."
                                                                                //OK
// Fuel related
#define TXT_Refuelling "~g~Abastecendo..."
#define TXT_PickupRefuel "Buzine\npara abastecer"
#define TXT_RefuelledVehicle "{00FF00}[Posto] {808080}Veiculo reabastecido por: {00FF00}R${FFFFFF}%i{808080}."
#define TXT_CannotRefuelVehicle "{FF0000}Sem dinheiro para abastecer o veiculo!"
                                                                                //OK
// Gametexts for loading/unloading
#define TXT_LoadingGoods "~n~~r~Carregando %s... ~n~~n~~w~Espere"
#define TXT_UnloadingGoods "~n~~r~Descarregando %s... ~n~~n~~w~Espere"
#define TXT_TruckerLoadingGoods "~n~~r~Carregando o caminhao... ~n~~n~~w~Espere"
#define TXT_TruckerUnloadingGoods "~n~~r~Descarregando o caminhao... ~n~~n~~w~Espere"
#define TXT_TransportingFromToPickup "~w~Transportando ~b~%s~w~ de ~r~%s~w~ para %s"
#define TXT_TransportingFromToDeliver "~w~Transportando ~b~%s~w~ de %s para ~r~%s~w~"
#define TXT_HaulingCargoFromToPickup "~w~Transporte ~b~%s~w~ de ~r~%s~w~ para %s"
#define TXT_HaulingCargoFromToDeliver "~w~Transporte ~b~%s~w~ de %s para ~r~%s~w~"   
#define TXT_PickupCargoAt "{00FF00}Carga: {FFFFFF}%s   {00FF00}Carregamento em: {FFFFFF}%s"
#define TXT_DeliverCargoTo "{00FF00}Carga: {FFFFFF}%s    {00FF00}Destino: {FFFFFF}%s"
                                                                                //OK
// Cardealer related
#define TXT_PickupCarDealer "Use \"/alugarcarro\"\npara alugar um carro"
#define TXT_BuyRentCarEmptyList "{FF0000}Lista vazia! O administrador pode ter desabilitado todos os veiculos desta classe."      
#define TXT_RentBike "Alugar bike:"
#define TXT_RentBoat "Alugar barco:"
#define TXT_RentConvertible "Alugar conversivel:"
#define TXT_RentHelicopter "Alugar helicoptero:"
#define TXT_RentIndustrial "Alugar veiculo industrail:"
#define TXT_RentLowRider "Alugar low-rider:"
#define TXT_RentOffRoad "Alugar off-road:"
#define TXT_RentPlane "Alugar aviao:"
#define TXT_RentPublicService "Alugar veiculo de servico publico:"
#define TXT_RentRC "Alugar radio control:"
#define TXT_RentSaloon "Alugar saloon:"
#define TXT_RentSport "Alugar sport:"
#define TXT_RentStationWagon "Alugar basicos:"
#define TXT_RentTrailer "Alugar trailer:"
#define TXT_RentUnique "Alugar veiculo unico:" 
#define TXT_AlreadyRentedVehicle "{FF0000}Você já tinha um veiculo alugado, mas foi substituido por um novo!"
#define TXT_PlayerRentsVehicle "{00FF00}Você alugou um {FFFF00}%s{00FF00} por R${FFFFFF}%i{00FF00}."
#define TXT_RentingTooExpensive "{FF0000}Você não dinheiro suficiente para alugar este veiculo!" 
#define TXT_BuyBike "comprar bike:"
#define TXT_BuyBoat "comprar barco:"
#define TXT_BuyConvertible "Comprar converssivel:"
#define TXT_BuyHelicopter "Comprar helicoptero:"
#define TXT_BuyIndustrial "Comprar veiculo industrial:"
#define TXT_BuyLowRider "Comprar low-rider:"
#define TXT_BuyOffRoad "Comprar off-road:"
#define TXT_BuyPlane "Comprar aviao:"
#define TXT_BuyPublicService "Comprar veiculo de servico publico:"
#define TXT_BuyRC "Comprar radio control:"
#define TXT_BuySaloon "Comprar saloon:"
#define TXT_BuySport "Comprar sport:"
#define TXT_BuyStationWagon "Comprar basicos:"
#define TXT_BuyTrailer "Comprar trailer:"
#define TXT_BuyUnique "Comprar veiculo unico:"      
                                                                                //OK
//---[Tempo preso]---
#define TXT_JailTimer "~w~Preso: ~r~%i~w~"
                                                                                //OK
//---[Velocimetro]---
#define TXT_SpeedometerSpeed "~w~Velocidade: ~b~%i~w~ km/h"
#define TXT_SpeedometerFuel "~w~Combustivel: %s"
#define TXT_SpeedometerCannotUseVehicle "{FF0000}Você não pode usar esse veiculo, ele pertence a {FFFFFF}%s{FF0000}."
#define TXT_SpeedometerClampedVehicle "{FF0000}Veiculo apreendido, você não pode usá-lo!"   
#define TXT_SpeedometerClampedVehicle2 "{FF0000}Para liberar o carro {FFFFFF}/liberar{FF0000}."
#define TXT_PlayerCaughtSpeeding "{FF0000}Você foi pêgo correndo acima da velocidade máxima permitida!" 
                                                                                //OK
// Toll-gate related
#define TXT_PlayerPaysToll "~n~_~n~_~n~_~n~~w~pedagio pago! ~n~~g~R$~w~%i"
                                                                                //OK
// Convoy related
#define TXT_PlayerStartsConvoy "{008040}[Comboio] {FFFFFF}%s{008040} iniciou um {FFFFFF}comboio{008040}, use {FFFFFF}/comboio{008040} se desejar entrar." 
#define TXT_PlayerJoinedConvoy "{008040}[Comboio] {FFFFFF}%s{008040} entrou no comboio."
#define TXT_YouJoinedConvoy "{008040}[Comboio] Você entrou no comboio!"
#define TXT_WaitingLeaderJob "{008040}Espere o lider do comboio inciar uma entrega..."
#define TXT_WaitingMembersToLoadCargo "{008040}Aguardando todos os membros do comboio se carregarem..."
#define TXT_WaitingMembersToUnLoadCargo "{008040}Aguardando todos os membros do comboio descarregarem..."         
#define TXT_ConvoyFull "{FF0000}[Comboio] O comboio está cheio!" 
#define TXT_ConvoyEnRoute "[Comboio] Esse comboio já está fretando, tente novamente depois de o comboio entregar o frete!"    
#define TXT_LeaderCancelledConvoy "{008040}[Comboio] O comboio foi {FF0000}cancelado{008040} pelo líder!"
#define TXT_MeetOtherConvoyMembers "{008040}[Comboio] Encontre os outros membros no ponto de carga."
#define TXT_ConvoyDistanceForLeader "{008040}Todos os membros precisam ficar {FF0000}500 metros{008040} perto de você."  
#define TXT_ConvoyDistanceForMember "{008040}Permanecer dentro de {FF0000}500 metros{008040} do líder do comboio."
#define TXT_MemberNeedsCargoTrailer "{FF0000}[Comboio] Você precisa de um {FFFFFF}TRAILER BAÚ{FF0000} para prosseguir." 
#define TXT_MemberNeedsOreTrailer "{FF0000}[Comboio] Você precisa de um {FFFFFF}TRAILER CAÇAMBA{FF0000} para prosseguir."
#define TXT_MemberNeedsFluidsTrailer "{FF0000}[Comboio] Você precisa de um {FFFFFF}TRAILER DE FLUÍDOS{FF0000} para prosseguir."
#define TXT_AllMembersSameTrailer "{008040}[Comboio] Todos os membros tem a mesma carroceria! {FFFFFF}Podem começar{008040}."
#define TXT_AllMembersNotSameTrailer "{008040}[Comboio] Nem todos os membros tem a mesma carroceria! {FFFFFF}O comboio não pode sair ainda{008040}."
#define TXT_AllMembersLoadedCargo "{008040}[Comboio] Todos os membros estão carregados, o comboio já pode avançar para o ponto de descarga."
#define TXT_MemberKickedByDistance "{FF0000}[Comboio] Você não ficou perto do líder e foi expulso do comboio automaticamente!"     
#define TXT_MemberFellBehind "{008040}[Comboio] {FFFFFF}%s{008040} ficou para trás e acabou sendo expulso do comboio."
#define TXT_FinishedConvoy "{008040}[Comboio] Você finalizou a entrega em comboio e ganhou {00FF00}R${FFFFFF}%i{008040}."
#define TXT_LeaderInfoBar "Membros: ~g~%i~w~, Membro mais distante: ~g~%s~w~, Distancia: ~r~%3.1f~w~metros"
#define TXT_MemberInfoBar "Lider: ~r~%s~w~, distancia: ~r~%3.1f~w~metros, membros: ~r~%i~w~"    
#define TXT_CannotJoinJobStarted "{FF0000}Você já começou um trabalho, você não pode criar ou participar de um comboio no momento!"
#define TXT_ConvoyAllreadyJoined "{FF0000}Você já está em um comboio!"
#define TXT_ConvoyNeedsTruckerClass "{FF0000}Você precisa ser um caminhoneiro para criar ou participar de um comboio!"
                                                                                //OK
// Timed messages
#define TXT_TimedRadio "{FF8080}Use /radio para ouvir as melhores rádios da internet."
#define TXT_TimedComboio "{FF8080}Use o comando /comboio para criar ou participar de um comboio."
#define TXT_TimedIrParaCasa "{FF8080}Já comprou sua casa? Em caso afirmativo use /irparacasa para abrir o menu das suas casas."
#define TXT_TimedNovidades "{FF8080}Use /novidades para saber sobre as novidades do servidor..."
#define TXT_TimedLicencas "{FF8080}Na auto-escola de San Fierro você pode comprar licenças de caminhão/ônibus e porte de armas."
#define TXT_TimedRadares "{FF8080}Fique atento aos radares! (60km/h cidade ,90km/h estradas, 120km/h rodovias)"
#define TXT_TimedIP "{FF8080}Não divulgue o 'Brasil Mega Trucker' em outros servidores, use as redes sociais. (Facebook, Orkut, Twiter, etc)"
#define TXT_TimedBlog "{FF8080}Acesse nosso blog e seja um seguidor. (brasilmegatrucker.blogspot.com)"
                                                                                //OK
// House-related
#define TXT_DefaultHouseName "Casa %s"
#define TXT_PlayerBoughtHouse "{00FF00}Casa adquirida. R${FFFFFF}%i{00FF00}." 
#define TXT_PlayerBoughtHouseTxT "~y~Casa adquirida! ~n~~g~R$~w~%i"             
#define TXT_PlayerOwnsMaxHouses "{FF0000}Limite de casas atingido!"
#define TXT_ExitHouseReloadEnv "Carregando espaco..."
#define TXT_PickupHouseOwned "%s\nDono: %s\nLevel da casa: %i\n\n{FFFFFF}/entrar" 
#define TXT_PickupHouseForSale "Valor da casa: R$%i\nNivel Max: %i\n\n{FF0000}/comprarcasa" 
#define TXT_DialogOldHouseName "{FF0000}Nome antigo da casa: %s"
#define TXT_DialogEnterNewHouseName "{00FF00}Insira o novo nome da sua casa:"
#define TXT_DialogSelectHouseUpgrade "Selecione a atualização:"
#define TXT_HouseReachedMaxLevel "{FF0000}Esta casa já está no level máximo, não pode atualizar ela mais."   
#define TXT_DialogBuyCarSelectClass "Selecione a classe de veiculo:"
#define TXT_HouseHasMaxVehicles "{FF0000}Esta casa não cabe mais carros!"  
#define TXT_AlreadyBoughtRecentVehicle "{FF0000}Você já comprou um veículo recentemente, use-o (/usarcarro) e em seguida estacione-o (/estacionar), para poder comprar outro."
#define TXT_EmptyCarSlot "%s{FFFFFF}vazio{FFFFFF}\n" 
#define TXT_SelectVehicleToSell "Selecione o veiculo ue irá vender:"
#define TXT_SelectVehicleToGet "Selecione o veiculo que irá usar:"
#define TXT_NoHouseVehicles "{FF0000}Sua casa não tem veículos ligados a ela!" 
#define TXT_SureSellHouse "Você tem certeza que deseja vender sua casa por R$%i?"  
#define TXT_AreYouSure "Tem certeza?"                                           
#define TXT_CannotSellHouseWithCars "{FF0000}Você não pode vender sua casa ainda, venda os carros existentes nela!" 
#define TXT_PlayerUpgradedHouse "{00FF00}Você atualizou sua casa para o level {FFFFFF}%i {00FF00}por {FFFFFF}R$%i{00FF00}."
#define TXT_CannotAffordUpgrade "{FF0000}Você não pode pagar pela atualização!" 
#define TXT_NoHouseInSlot "{FF0000}Slot vazio!"
#define TXT_ChangedHouseName "{00FF00}Você alterou o nome da sua casa!"             
#define TXT_PlayerBoughtVehicle "{00FF00}Você comprou um(a) {FFFFFF}%s{00FF00} por R${FFFFFF}%i{00FF00}." 
#define TXT_PlayerMustUseGetcarAndPark "{00FF00}Agora saia da casa e use {FFFFFF}/usarcarro{00FF00} para criá-lo, depois use {FFFFFF}/estacionar{00FF00} no local que desejar."
#define TXT_PlayerMustUsePark "{00FF00}Você gerou seu veículo, agora use {FFFFFF}/estacionar{00FF00} para estacioná-lo em sua casa."
#define TXT_CannotAffordVehicle "{FF0000}Você não pode pagar por esse veículo!"
#define TXT_PlayerSoldHouse "{FF0000}Casa vendida!"
#define TXT_PlayerSellHouseTxT "~r~Casa vendida!~n~~g~R$~w~%i"                  
#define TXT_PlayerSoldVehicle "{00FF00}Você vendeu seu(sua) {FFFFFF}%s{00FF00} por R${FFFFFF}%i{00FF00}."
#define TXT_NoVehicleInSlot "{FF0000}Não existe veículo nesse slot!" 
#define TXT_DialogTitleBuyInsurance "Comprar seguro?"
#define TXT_DialogBuyInsurance "Você tem certeza que deseja comprar o seguro dos veículos por R$%i?"
#define TXT_HouseAlreadyHasInsurance "{FF0000}Esta casa já tem seguro dos veículos."
#define TXT_PlayerBoughtInsurance "{00FF00}Você pagou R${FFFFFF}%i{00FF00} pelo seguro dos veículos!"
#define TXT_CannotAffordInsurance "{FF0000}Você não tem dinheiro para pagar o seguro!"
                                                                                //OK
// Business related
#define TXT_PickupBusinessOwned "%s\nDono: %s\nLevel: %i\n\n{FFFFFF}/entrar"
#define TXT_PickupBusinessForSale "%s\nValor da empresa: R$%i\nGanhos: R$%i\n\n{FF0000}/comprarempresa"
#define TXT_DefaultBusinessName "Empresa %s"     
#define TXT_PlayerBoughtBusiness "{00FF00}Você comprou a empresa por R${FFFFFF}%i{00FF00}."
#define TXT_PlayerBoughtBusinessTxT "~y~Empresa adquirida!~n~~g~R$~w~%i"
#define TXT_PlayerOwnsMaxBusinesses "{FF0000}Limite de empresas atingido!"
#define TXT_NoBusinessInSlot "{FF0000}Não há empresa nesse slot."
#define TXT_DialogOldBusinessName "{00FF00}Nome antigo da empresa: %s"
#define TXT_DialogEnterNewBusinessName "{FF0000}Insira o novo nome da empresa:" 
#define TXT_ChangedBusinessName "{00FF00}Você alterou o nome da sua empresa!"
#define TXT_BusinessReachedMaxLevel "{FF0000}Sua empresa já está no level máximo!"
#define TXT_SureSellBusiness "Você deseja vender seu negócio por R$%i?"
#define TXT_PlayerSoldBusiness "{FF0000}Empresa vendida!"
#define TXT_PlayerSellBusinessTxT "~r~Empresa vendida!~n~~g~R$~w~%i"
                                                                                //OK
